[project]
name = "moonshot-python-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "paramiko>=4.0.0",
    "pendulum>=3.1.0",
    "requests>=2.32.4",
]
